2D-b

py.test
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-4.1.0, py-1.7.0, pluggy-0.8.1
rootdir: /home/luismiguel/bitbucket/py_pol, inifile: pytest.ini
collected 105 items

tests/test_drawing.py ...........                                        [ 10%]
tests/test_jones_matrix.py ............                                  [ 21%]
tests/test_jones_matrix_parameters.py ......                             [ 27%]
tests/test_jones_vector.py .............                                 [ 40%]
tests/test_jones_vector_parameters.py ..                                 [ 41%]
tests/test_mueller.py ......................                             [ 62%]
tests/test_mueller_check_analysis.py ............                        [ 74%]
tests/test_mueller_parameters.py ............F...                        [ 89%]
tests/test_stokes.py .F.....                                             [ 96%]
tests/test_stokes_parameters.py .                                        [ 97%]
tests/test_utils.py ...                                                  [100%]

=================================== FAILURES ===================================
________________ TestMueller_parameters.test_retardance_vector _________________

self = <tests.test_mueller_parameters.TestMueller_parameters object at 0x7f592fdd5c50>

    def test_retardance_vector(self):
        D = np.pi * np.random.rand(1)
        D = D[0]
        ur = np.random.rand(3)
        ur = ur / np.linalg.norm(ur)
        solution = ur
        M1 = Mueller('M1')
        M1.retarder_from_vector(D, ur, kind='norm')
>       proposal = M1.parameters.retardance_vector(kind='norm')
E       AttributeError: 'Parameters_Mueller' object has no attribute 'retardance_vector'

tests/test_mueller_parameters.py:168: AttributeError
______________________________ TestStokes.test_E _______________________________

self = <tests.test_stokes.TestStokes object at 0x7f592fd012b0>

    def test_E(self):
        t = np.linspace(0, 6 * np.pi, 100)
        E = np.zeros((len(t), 3), dtype=complex)
        E[:, 0] = 1 * np.sin(t)
        E[:, 1] = 1 * np.sin(t)
        E[:, 2] = np.zeros_like(E[:, 2])

        solution = matrix([[1], [0], [1], [0]])

        M1 = Stokes('from_elements')
        M1.from_distribution(E)
        proposal = M1.get()
>       assert comparison(
            proposal, solution, eps
        ), sys._getframe().f_code.co_name + ".py --> example: (1, 0, 1, 0)"
E       AssertionError: test_E.py --> example: (1, 0, 1, 0)
E       assert False
E        +  where False = comparison(matrix([[5.13015188e-29],\n        [0.00000000e+00],\n        [5.13015188e-29],\n        [0.00000000e+00]]), matrix([[1],\n        [0],\n        [1],\n        [0]]), 1e-06)

tests/test_stokes.py:45: AssertionError
=============================== warnings summary ===============================
tests/test_drawing.py::TestDrawing::test_ellipse_stokes_probabilities
  /home/luismiguel/.local/lib/python3.6/site-packages/matplotlib/contour.py:1243: UserWarning: No contour levels were found within the data range.
    warnings.warn("No contour levels were found"

tests/test_drawing.py::TestDrawing::test_ellipse_jones_several1
  /home/luismiguel/bitbucket/py_pol/py_pol/jones_vector.py:803: RuntimeWarning: invalid value encountered in sqrt
    b = np.sqrt(b2)

tests/test_mueller_check_analysis.py::TestMueller_checks::test_is_homogenous
  /home/luismiguel/bitbucket/py_pol/py_pol/mueller.py:1588: RuntimeWarning: invalid value encountered in sqrt
    return sqrt(eta)

tests/test_mueller_check_analysis.py::TestMueller_analysis::test_filter_physical_conditions
  /home/luismiguel/bitbucket/py_pol/py_pol/mueller.py:557: ComplexWarning: Casting complex values to real discards the imaginary part
    M[i, j] = elem

tests/test_mueller_parameters.py::TestMueller_parameters::test_inhomogeneity
  /home/luismiguel/bitbucket/py_pol/py_pol/mueller.py:1581: RuntimeWarning: invalid value encountered in cdouble_scalars
    ) / sqrt(m00 + M[1, 1] + M[1, 0] + M[0, 1])

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============== 2 failed, 103 passed, 5 warnings in 20.50 seconds ===============
Makefile:57: recipe for target 'test' failed
